module.exports = {
  projects: [
    '<rootDir>/apps/spotify',
    '<rootDir>/libs/web/layout',
    '<rootDir>/libs/web/nav-bar',
    '<rootDir>/libs/web/browse/features/categories',
    '<rootDir>/libs/web/main-view',
    '<rootDir>/libs/web/now-playing-bar',
    '<rootDir>/libs/web/shared/ui/play-button',
    '<rootDir>/libs/web/auth',
    '<rootDir>/libs/web/store',
    '<rootDir>/libs/apis',
    '<rootDir>/libs/spotify-route',
    '<rootDir>/libs/web/top-bar',
    '<rootDir>/libs/web/shared/app-config',
    '<rootDir>/libs/web/home',
    '<rootDir>/libs/web/recent-played',
    '<rootDir>/libs/web/song',
    '<rootDir>/libs/callback',
    '<rootDir>/libs/web/shared/models',
    '<rootDir>/libs/web/shared/utils',
    '<rootDir>/libs/web/browse/features/search',
    '<rootDir>/libs/web/shared/ui/play-list',
  ],
};
